title: Lloyd Chess Engine - Benchmarks
description: Performance benchmark tracking for Lloyd chess engine
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
github:
  repository_url: https://github.com/tenpointtw0/Lloyd.Docs

# Navigation
header_pages:
  - README.md

# Show excerpts on homepage
show_excerpts: true
